name: geocat_viz_build
channels:
  - conda-forge
dependencies:
  - python>=3.8, <=3.10
  - cartopy
  - make
  - matplotlib<=3.5
  - sphinx
  - pip
  - cmaps
  - numpy
  - xarray<=2023.02.0 #pin per issue https://github.com/NCAR/geocat-comp/issues/381
  - metpy
  - pint
  - geocat-datafiles
  - pip:
    - pre-commit
    - scikit-learn
