name: geocat_viz_upstream
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - geocat-comp
  - cf_xarray>=0.3.1
  - geocat-datafiles
  - eofs
  - fiona
  - geocat-viz
  - cartopy
  - geographiclib
  - jupyter
  - jupyterlab
  - make
  - matplotlib<3.6
  - metpy
  - mock
  - myst-nb
  - nbsphinx
  - netcdf4
  - pillow
  - pint
  - pip
  - scikit-learn
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
  - sphinx-design
  - sphinx-book-theme
  - wrf-python
  - xarray<=2023.02.0 # pinned as per issue #98
  - pre-commit
  - geocat-datafiles # for examples/tests
