name: Upstream Examples CI - experimental
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run:
    name: Build GeoCAT-examples (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
        python-version: [ "3.7", "3.9" ]

    steps:
    - uses: actions/checkout@v2
    - name: Install GeoCAT-examples
      run: |
        git clone https://github.com/NCAR/GeoCAT-examples.git
        git checkout experimental-features

    - name: Create geocat-examples environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        micromamba-version: "latest"
        environment-name: geocat-examples
        environment-file: ./GeoCAT-examples/conda_environment.yml

    - name: Install geocat-viz
      run: |
        python -m pip install --no-deps --ignore-installed -vv .

    - name: make html
      working-directory: ./GeoCAT-examples/docs
      run: |
        conda info
        conda list
        make html
