name: Upstream Examples CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”
  workflow_dispatch:


jobs:
  build-and-run:
    name: Build GeoCAT-examples (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
        python-version: ["3.8", "3.9", "3.10" ]

    steps:
    - uses: actions/checkout@v2
    - name: Install GeoCAT-examples
      run: |
        git clone https://github.com/NCAR/GeoCAT-examples.git

    - name: Create geocat-examples environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        micromamba-version: "latest"
        environment-name: geocat_viz_upstream
        environment-file: build_envs/upstream_environment.yml

    - name: Install geocat-viz
      run: |
        python -m pip install --no-deps --ignore-installed -vv .

    - name: make html
      working-directory: ./GeoCAT-examples/docs
      run: |
        conda info
        conda list
        make html
